SELECT
  pjpub.MSP_WORKFLOW_PHASES.PHASE_NAME AS [Phase Name],
  pjpub.MSP_WORKFLOW_STAGES.STAGE_NAME AS [Stage Name],
  pjpub.MSP_WORKFLOW_STAGES.STAGE_DESCRIPTION,
  pjpub.MSP_WORKFLOW_STAGE_PDPS.PDP_NAME AS 'Visiable Project Detail Pages',
  (SELECT
    [pjpub].[MSP_PDP_INFO].PDP_DISPLAY_NAME
  FROM [pjpub].[MSP_PDP_INFO]
  WHERE PDP_UID = pjpub.MSP_WORKFLOW_STAGES.STATUS_PDP_UID)
  AS 'Workflow Stage Status PDP',
  pjpub.MSP_WORKFLOW_STAGES.STAGE_SUBMIT_DESCRIPTION as 'Description for Submit',
  pjpub.MSP_WORKFLOW_STAGE_PDPS.PDP_STAGE_DESCRIPTION 'Workflow Stage Specific Desciption',
  CASE
    WHEN pjpub.MSP_WORKFLOW_STAGE_PDPS.PDP_REQUIRES_ATTENTION = '0' THEN 'No'
    ELSE 'Yes'
  END AS 'The Project Detail Page requires attention',
  ISNULL(pjpub.MSP_CUSTOM_FIELDS.MD_PROP_NAME, 'Not Set') AS 'Cusotm Field Name',
  CASE
    WHEN pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.REQUIRED = '0' THEN 'No'
    WHEN pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.REQUIRED = '1' THEN 'Yes'
    ELSE 'Not Set'
  END AS 'Required Custom Fields',
  CASE
    WHEN pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.READ_ONLY = '0' THEN 'No'
    WHEN pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.READ_ONLY = '1' THEN 'Yes'
    ELSE 'Not Set'
  END AS 'ReadOnly Custom Fields',
  CASE
    WHEN pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT.BEHAVIOR = '0' THEN 'Read Only'
    WHEN pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT.BEHAVIOR = '1' THEN 'Read & Write'
    WHEN pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT.BEHAVIOR = '2' THEN 'Required'
  END AS 'Stratgic Impact Behavior',
  CASE
    WHEN pjpub.MSP_WORKFLOW_STAGES.CHECKIN_REQUIRED = '0' THEN 'No'
    ELSE 'Yes'
  END AS [Check In required]
FROM pjpub.MSP_CUSTOM_FIELDS
INNER JOIN pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS
  ON pjpub.MSP_CUSTOM_FIELDS.SiteId = pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.SiteId
  AND pjpub.MSP_CUSTOM_FIELDS.MD_PROP_UID = pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.MD_PROP_UID
RIGHT OUTER JOIN pjpub.MSP_WORKFLOW_PHASES
INNER JOIN pjpub.MSP_WORKFLOW_STAGES
  ON pjpub.MSP_WORKFLOW_PHASES.SiteId = pjpub.MSP_WORKFLOW_STAGES.SiteId
  AND pjpub.MSP_WORKFLOW_PHASES.PHASE_UID = pjpub.MSP_WORKFLOW_STAGES.PHASE_UID
INNER JOIN pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT
  ON pjpub.MSP_WORKFLOW_STAGES.SiteId = pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT.SiteId
  AND pjpub.MSP_WORKFLOW_STAGES.STAGE_UID = pjpub.MSP_WORKFLOW_STAGE_STRATEGIC_IMPACT.STAGE_UID
INNER JOIN pjpub.MSP_WORKFLOW_STAGE_PDPS
  ON pjpub.MSP_WORKFLOW_STAGES.SiteId = pjpub.MSP_WORKFLOW_STAGE_PDPS.SiteId
  AND pjpub.MSP_WORKFLOW_STAGES.STAGE_UID = pjpub.MSP_WORKFLOW_STAGE_PDPS.STAGE_UID
  ON pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.SiteId = pjpub.MSP_WORKFLOW_STAGES.SiteId
  AND pjpub.MSP_WORKFLOW_STAGE_CUSTOM_FIELDS.STAGE_UID = pjpub.MSP_WORKFLOW_STAGES.STAGE_UID
ORDER BY [Phase Name], [Stage Name]